---
apiVersion: 1
datasources:
  - access: proxy
    editable: true
    name: graphql
    orgId: 1
    type: fifemon-graphql-datasource
    url: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet
    version: 1

